### ISSUE TITLE
Official OpenPose vd OpenPose without PFA

### ISSUE THREAD

**Issue by Michele1996** [FORTH-ModelBasedTracker/MocapNET#77] opened 2022-03-31 14:34 UTC
Hi, I'm currently use MocapNET and OpenPose to create a BVH using some videos. I've tried the MocapNET2LiveDemo with --openpose flag and also the official implementation of OpenPose to generate BVH of the same videos and I notice some differences  and sometimes LiveDemo perform better. 

Is it possible to know where MocapNET2LiveDemo place de json file coming from the --openpose treatement in order to save them in another folder? 
Thank you!

**Comment by AmmarkoV** [comment] 2022-04-02 08:21
Hello the homebrewed Openpose implementation is  not using json at all it is a .pb model trained from scratch and loaded using the intialize script (https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/initialize.sh#L164)  and the retrieved 2d heatmaps are converted to 2D points using the 2d Joint Estimator here (https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/src/JointEstimator2D/jointEstimator2D.cpp). Btw I am also working on a mediapipe front end to do both hands and body in the live demo however due to being involved in a very demanding project I need some time to introduce the new code in this repo

**Comment by Michele1996** [comment] 2022-04-07 10:21
Hi thank you for the answer!
I would like to ask you another question about the performance.
I mean, If I use openPose to get the keypoints and after I use MocapNET to get the bvh (for example using the shuffle.webm example) I don't get the same results of the liveDemo which is almost perfect while the other one is far from the real animation.
Is there a reason for that?

**Comment by AmmarkoV** [comment] 2022-04-08 11:33
Hello!

The neural network is the same, so no matter the source it should run the same (and actually better using the full OpenPose implementation)..
Now since by altering the 2D joint quality you have observed that it negatively affects the 3D output my guess is that your issue is actually the following : 

MocapNET is trained using a 1920x1080 "virtual camera" that tries to emulate a [GoPRO Hero 4 running at the Full-HD](https://github.com/AmmarkoV/RGBDAcquisition/blob/master/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/Applications/BVHTester/main.c#L431) mode. Keeping this in mind (since the closest you get to this configuration the better the Neural Network will respond) 

Now depending on your setup, I am guessing that your problem has to do with the input dimensions provided to the converter tool as seen in the documentation of the [convertOpenPoseJSONToCSV](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/src/MocapNET2/Converters/Openpose/convertOpenPoseJSONToCSV.cpp#L30) tool..

It can be caused by not providing the correct dimensions of your input. For example giving the parameters [--size 1920 1080](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/src/MocapNET1/MocapNETFromJSON/mocapnetJSON.cpp#L194) for a 1920x1080 stream. This might seem trivial but since the neural network relies on normalized coordinates supplying a wrong frame size destroys the normalization and can lead to very weird artifacts that will notably degrade quality..! 

A similar issue is for example if you supply a portrait video feed of let's say 1080x1920 pixels with the same focal length the aspect ratio of the 2D points will be 0.56 instead of 1.77 and  this will have a huge impact on the generated NSRM matrices that will no longer follow the same distributions as the trained data.. To combat this I have an automatic mechanism (see [normalizeWhileAlsoMatchingTrainingAspectRatio](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/src/MocapNET2/MocapNETLib2/IO/jsonMocapNETHelpers.cpp#L176) call) that tries to embed the given 2D points in a larger canvas that follows the training dimensions to somehow make this more transparent for the end-users.. 

In any case I think that by providing the dimensions of the 2D image and ideally if the source image dimensions are 1920x1080 you will achieve the best results!

**Comment by AmmarkoV** [comment] 2022-06-17 15:17
I have added a Mediapipe wrapper (instead of OpenPose) that will probably also help you so closing the issue !

**Closed as completed by AmmarkoV** 2022-06-17 15:17 UTC
Labels: documentation, question
