### ISSUE TITLE
Tensorflow v2.3 and CUDA 12.0

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [FORTH-ModelBasedTracker/MocapNET#105] opened 2023-07-24 20:01 UTC
My PC has CUDA 12.0 and I installed tensorflow v2.3.
But it seems not to run as expected.
Please tell me how to run on CUDA 12.0 and tensorflow v2.x.

**Comment by AmmarkoV** [comment] 2023-07-25 10:33
Hello this is actually a duplicate of https://github.com/FORTH-ModelBasedTracker/MocapNET/issues/101
so I am closing it and answering it there

**Closed as completed by AmmarkoV** 2023-07-25 10:33 UTC
Labels: duplicate, nvidiaproblems, tensorflow problems
