### ISSUE TITLE
Please, can you give us a video explaining how to install and run this program?

### ISSUE THREAD

**Issue by 2655251820** [FORTH-ModelBasedTracker/MocapNET#55] opened 2021-04-25 04:09 UTC
Because I don’t understand the code, and I don’t know how to install and configure the code running environment, you have explained it, but it is difficult for us who do not understand the code in non-English speaking countries to understand what you have done. If it is convenient, you can Can I explain this in a video? My friends and I are very interested, even though they don’t understand the code

**Comment by 2655251820** [comment] 2021-04-25 04:09
And how to connect to Blender, this is our most concerned issue

**Comment by AmmarkoV** [comment] 2021-05-10 10:01
Hello, thanks for opening the issue..!
it is true that setting up the project can be daunting if you don't have experience with CMake etc.

First of all I will create a youtube video going over the setup of the project as you requested, however due to currently having various deadlines this will probably happen around June!

To create a realistic rendering of a human in blender you can use : 
A) [Makehuman](http://www.makehumancommunity.org/) 
B) My [CMU+Face](http://www.makehumancommunity.org/content/cmu_plus_face.html ) Rig
C) [Blender](https://www.blender.org/)
D) [The Makehuman plugin for Blender for Makehuman](https://github.com/makehumancommunity/makehuman-plugin-for-blender)
E) [The Makehuman plugin for Blender for Blender](https://github.com/makehumancommunity/makehuman-plugin-for-blender/blob/master/blender_distribution/MH_Community_for_blender_280.zip?raw=true) 
F) [The Makewalk plugin for Blender](https://github.com/psemiletov/makewalk)
G) A BVH file, even if you cant get MocapNET to compile you can download and try some of the [CMU BVH files](http://ammar.gr/datasets/CMUPlusHeadMotionCapture.zip) ..  


Using all these you can create a 3D avatar with the appropriate rigging, directly import it in blender and then using the makewalk plugin automatically retarget it with the BVH file..

However you can also open a BVH file directly with blender 
![screen-2021-05-10-13-07-25](https://user-images.githubusercontent.com/97630/117643067-aebd9880-b190-11eb-8f7d-ca710c6e1fbe.jpg)
![screen-2021-05-10-13-09-47](https://user-images.githubusercontent.com/97630/117643408-08be5e00-b191-11eb-83d2-73294ccee0d3.jpg)

and then set up your own rigging to your model
Unfortuntely I dont know your Blender/3D animation expertise but I think the above is a good overview to answer your questions

**Comment by nowhereman1999** [comment] 2022-01-27 13:21
@AmmarkoV Hi,I'm a undergratuate from China and I have attended the Adaptive Computing Challenge 2021
with Xilinx and I want to use the KV260 AI starterkit to make a mocap which Iead me to find your project，I can‘t install your MocapNET directly using the initialize.sh script which shown in this picture:
![image](https://user-images.githubusercontent.com/53631206/151365907-f186491a-8c3c-4211-b697-a8e5d4691bb7.png)
I'm not sure if it is caused by the architecture of KV260，I checked the shell script and found it was mainly download some pretrained model and configure the environment of the platform.And the xilinx's vitis-ai repository have intergrated the openpose model,So I want to ask you how you finally generate the BVH files through MocapNET and I wonder if I can use the openpose model in the vitis library to achieve it too,I would appreciate it if you can give a reply:-)

**Comment by AmmarkoV** [comment] 2022-01-31 10:11
I moved the issue of @Hezhexi2002  to a new issue so that it is not mixed with the making a video issue..

**Comment by nowhereman1999** [comment] 2022-02-07 02:50
> I moved the issue of @Hezhexi2002  to a new issue so that it is not mixed with the making a video issue..

OK，thanks a lot，I'm so sorry that I don't reply you in time because recently we have celebrated the Spring Festival in China，I will soon check the new issue and try it again:-)

**Comment by socketing** [comment] 2022-02-27 12:24
> 

我将用中文与你沟通，方便告诉我你的VX或者QQ吗，这样更方便我们交流。

**Comment by socketing** [comment] 2022-02-27 12:24
@Hezhexi2002

**Comment by nowhereman1999** [comment] 2022-02-27 13:05
> > 
> 
> 我将用中文与你沟通，方便告诉我你的VX或者QQ吗，这样更方便我们交流。

用微信吧，主要是我也没有在本地跑起来过，但是我现在主要是想移植到kv260上![mmqrcode1645967052419.png](https://user-images.githubusercontent.com/53631206/155883578-306d7fed-cba5-485c-92ad-603755ecbecd.png)

**Comment by AmmarkoV** [comment] 2022-12-30 19:06
Hello
I added a video, so after a long while closing this issue :) !


[![YouTube Link](https://raw.githubusercontent.com/FORTH-ModelBasedTracker/MocapNET/master/doc/blenderytb.png)](https://www.youtube.com/watch?v=ooLRUS5j4AI)

**Closed as completed by AmmarkoV** 2022-12-30 19:06 UTC
Labels: documentation, help wanted
