### ISSUE TITLE
libopencv_freetype.so.3.2.0: error: undefined reference / Project Not Working on Google Collab

### ISSUE THREAD

**Issue by saksham117** [FORTH-ModelBasedTracker/MocapNET#38] opened 2020-10-28 18:49 UTC
Hi.
So, by referring to a previous issue ( #33 ) , I tried to run this on Google Collab.
Here is the link to my Google Collab Notebook
https://colab.research.google.com/drive/1-j-EhXFmeKO7EONP-DiHIEGomu20n9vn?usp=sharing

However I ran into another problem while running the initialization scripts.

```

Scanning dependencies of target ReshapeCSV
[ 37%] Building CXX object src/MocapNET2/reshapeCSVFileToMakeClassification/CMakeFiles/ReshapeCSV.dir/reshapeCSV.cpp.o
[ 37%] Linking CXX executable ../../../../ReshapeCSV
/usr/lib/x86_64-linux-gnu/libopencv_freetype.so.3.2.0: error: undefined reference to 'FT_Set_Pixel_Sizes'
/usr/lib/x86_64-linux-gnu/libopencv_freetype.so.3.2.0: error: undefined reference to 'hb_shape'
/usr/lib/x86_64-linux-gnu/libopencv_freetype.so.3.2.0: error: undefined reference to 'FT_Load_Glyph'
/usr/lib/x86_64-linux-gnu/libopencv_freetype.so.3.2.0: error: undefined reference to 'hb_buffer_guess_segment_properties'
/usr/lib/x86_64-linux-gnu/libopencv_freetype.so.3.2.0: error: undefined reference to 'hb_ft_font_create'
/usr/lib/x86_64-linux-gnu/libopencv_freetype.so.3.2.0: error: undefined reference to 'FT_Outline_Transform'
/usr/lib/x86_64-linux-gnu/libopencv_freetype.so.3.2.0: error: undefined reference to 'hb_buffer_destroy'
/usr/lib/x86_64-linux-gnu/libopencv_freetype.so.3.2.0: error: undefined reference to 'FT_Init_FreeType'
/usr/lib/x86_64-linux-gnu/libopencv_freetype.so.3.2.0: error: undefined reference to 'FT_Outline_Decompose'
/usr/lib/x86_64-linux-gnu/libopencv_freetype.so.3.2.0: error: undefined reference to 'FT_Outline_Translate'
/usr/lib/x86_64-linux-gnu/libopencv_freetype.so.3.2.0: error: undefined reference to 'hb_font_destroy'
/usr/lib/x86_64-linux-gnu/libopencv_freetype.so.3.2.0: error: undefined reference to 'FT_Done_FreeType'
/usr/lib/x86_64-linux-gnu/libopencv_freetype.so.3.2.0: error: undefined reference to 'hb_buffer_add_utf8'
/usr/lib/x86_64-linux-gnu/libopencv_freetype.so.3.2.0: error: undefined reference to 'hb_buffer_get_glyph_infos'
/usr/lib/x86_64-linux-gnu/libopencv_freetype.so.3.2.0: error: undefined reference to 'FT_New_Face'
/usr/lib/x86_64-linux-gnu/libopencv_freetype.so.3.2.0: error: undefined reference to 'FT_Render_Glyph'
/usr/lib/x86_64-linux-gnu/libopencv_freetype.so.3.2.0: error: undefined reference to 'FT_Done_Face'
/usr/lib/x86_64-linux-gnu/libopencv_freetype.so.3.2.0: error: undefined reference to 'hb_buffer_create'
collect2: error: ld returned 1 exit status
src/MocapNET2/reshapeCSVFileToMakeClassification/CMakeFiles/ReshapeCSV.dir/build.make:127: recipe for target '../ReshapeCSV' failed
make[2]: *** [../ReshapeCSV] Error 1
CMakeFiles/Makefile2:145: recipe for target 'src/MocapNET2/reshapeCSVFileToMakeClassification/CMakeFiles/ReshapeCSV.dir/all' failed
make[1]: *** [src/MocapNET2/reshapeCSVFileToMakeClassification/CMakeFiles/ReshapeCSV.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

```

Please take a look at this.

P. S.

Thanks for this great repo and sharing it with the world. Its simply awesome.

**Comment by ghildebrandt** [comment] 2020-10-28 19:13
Hello,

i face the same problem on a fairly clean install of Ubuntu 18.04 where only OpenPose has been built. Same errror output.

**Comment by AmmarkoV** [comment] 2020-10-29 12:29
I think this is caused by the "gold" linker, please try pulling and rebuilding, I think it should work now..

**Comment by ghildebrandt** [comment] 2020-10-29 16:39
I have tried to build it and can confirm it worked

**Comment by AmmarkoV** [comment] 2020-10-30 10:00
This is confirmed fixed, so I am closing the issue..!

**Closed as completed by AmmarkoV** 2020-10-30 10:00 UTC
Labels: fixed, build problems

**Comment by saksham117** [comment] 2020-11-01 11:51
Thanks a lot Ammar.
Its now working perfectly fine!!!
