### ISSUE TITLE
Two issues about TF saved model in branch mnet3

### ISSUE THREAD

**Issue by polwer** [FORTH-ModelBasedTracker/MocapNET#69] opened 2022-01-16 10:13 UTC
There are two issues about Branch mnet3:
First in initialize.sh line 143:
`mkdir -p combinedModel/mocapnet2/mode1/1.0/
cd "$DIR/dataset/combinedModel/mocapnet2/mode5/1.0/"
wget http://ammar.gr/datasets/bmvc2021/mnet3Ensemble.zip
unzip mnet3Ensemble.zip`.
It makes directory '../mode1/1.0/' ,but unpacked mnet3Ensemble.zip into '../mode5/1.0/'.
Second, I unpacked mnet3Ensemble.zip and get four TF2 saved model folders,and tested loading them by TF python api and get error:
```
'Failed to find any matching files for /MocapNET/dataset/1.0/upperbody_all.pb/variables/variables'
```
The upperbody_all.pb/variables/variables and other's variables folder is empty.'
Then I test load and predict models with C api with MocapNET3's code, I get load error:
`'The specified SavedModel has no variables; no checkpoints were restored. File does not exist: /MocapNET/dataset/1.0/lhand_all.pb/variables/variables.index'`
and predict error:
```
'tf2_run: Error running network, Error while reading resource variable finger1-2.l_Xrotation_50_layer_10/bias from Container: localhost. This could mean that the variable was uninitialized. Not found: Container localhost does not exist. (Could not find resource: localhost/finger1-2.l_Xrotation_50_layer_10/bias)
         [[{{node model/finger1-2.l_Xrotation/finger1-2.l_Xrotation_50_layer_10/BiasAdd/ReadVariableOp}}]]'
```

The version of TensorFlow python is 2.3.1 and  TensorFlow C also.

**Comment by AmmarkoV** [comment] 2022-01-17 08:29
Hello, thanks for opening the issue I will try to resolve it ASAP

**Comment by AmmarkoV** [comment] 2022-01-17 12:35
Once again thank you for reporting the issue, for some reason  the zip command ignored files in the second level directories of the model files so they didn't get included!
I switched back to tarballs so the new path for the models is  ( http://ammar.gr/datasets/bmvc2021/mnet3Ensemble.tar.gz ) and I double checked it and seems to be loading correctly now..!

I have appended the appropriate [corrections on the initialize.sh script](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/mnet3/initialize.sh#L148) 

While on the main directory where the initialize.sh script lies if you perform the following 
three commands, it should "work" now! 
 
```
wget http://ammar.gr/datasets/signumtest.zip

unzip signumtest.zip

./MocapNET2CSV --from con0014/2dJoints_v1.4.csv --ik 0.001 15 30 --mt --show 3  --hands --label s10-p01-c0014-f --seriallength 4 --gdpr
```

I am leaving this issue open waiting for your confirmation that the issue is fixed..!
In case it doesn't or you encounter another issue please comment here or open a new issue with the problem so I can fix it!

**Comment by quyanqiu** [comment] 2022-01-17 13:49
Yes it worked! But following error occur:

2022-01-17 21:36:27.189666: W tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at conv_ops_fused_impl.h:697 : Not found: No algorithm worked!
predictTensorflowOnArrayOfHeatmaps: Error running session 5 ( 2 root error(s) found.
  (0) Not found: No algorithm worked!
	 [[{{node activation_1/Relu}}]]
  (1) Not found: No algorithm worked!
	 [[{{node activation_1/Relu}}]]
	 [[k2tfout_1/_3]]
0 successful operations.
0 derived errors ignored. ) 

I am using libTensorflow2.4 and cuda11 need help sir

**Comment by quyanqiu** [comment] 2022-01-17 14:05
> Yes it worked! But following error occur:
> 
> 2022-01-17 21:36:27.189666: W tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at conv_ops_fused_impl.h:697 : Not found: No algorithm worked! predictTensorflowOnArrayOfHeatmaps: Error running session 5 ( 2 root error(s) found. (0) Not found: No algorithm worked! [[{{node activation_1/Relu}}]] (1) Not found: No algorithm worked! [[{{node activation_1/Relu}}]] [[k2tfout_1/_3]] 0 successful operations. 0 derived errors ignored. )
> 
> I am using libTensorflow2.4 and cuda11 need help sir



I found python solution as follow,But how to set in Tensorflow C_api?
Adding the code below right after the imports solved the issue for me ! Thanks !

    physical_devices = tf.config.list_physical_devices(‘GPU’)
    tf.config.experimental.set_memory_growth(physical_devices[0], True)

**Comment by AmmarkoV** [comment] 2022-01-17 16:54
Unfortunately the Tensorflow stuff has a lot of weird behaviors, typically if you dont use a very recent version and you google errors (like what you did) there are small workarounds..!

For the C API what I have written from scratch as a TF2 wrapper is this 
https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/mnet3/src/Tensorflow2/tensorflow2.h

I have the [tf2_setCPUExecutionSessionConfiguration](
https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/mnet3/src/Tensorflow2/tensorflow2.h#L159) function to do GPU/CPU switching which uses a "hack" to get the raw binary internal representation of tensorflow and do a "compatible" call..!

There is no other official way to do this :( 

In any case since you managed to use/run the code I am closing this issue!

Thank you again for pointing the mistaken model packaging

**Closed as completed by AmmarkoV** 2022-01-17 16:54 UTC
Labels: bug, fixed, build problems

**Comment by quyanqiu** [comment] 2022-01-18 02:15
> Unfortunately the Tensorflow stuff has a lot of weird behaviors, typically if you dont use a very recent version and you google errors (like what you did) there are small workarounds..!
> 
> For the C API what I have written from scratch as a TF2 wrapper is this https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/mnet3/src/Tensorflow2/tensorflow2.h
> 
> I have the [tf2_setCPUExecutionSessionConfiguration](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/mnet3/src/Tensorflow2/tensorflow2.h#L159) function to do GPU/CPU switching which uses a "hack" to get the raw binary internal representation of tensorflow and do a "compatible" call..!
> 
> There is no other official way to do this :(
> 
> In any case since you managed to use/run the code I am closing this issue!
> 
> Thank you again for pointing the mistaken model packaging

I change libTensorFlow to 2.6 and Use CUDA11.2 it worked!
Thanks dude

**Comment by polwer** [comment] 2022-01-18 02:28
> Unfortunately the Tensorflow stuff has a lot of weird behaviors, typically if you dont use a very recent version and you google errors (like what you did) there are small workarounds..!
> 
> For the C API what I have written from scratch as a TF2 wrapper is this https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/mnet3/src/Tensorflow2/tensorflow2.h
> 
> I have the [tf2_setCPUExecutionSessionConfiguration](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/mnet3/src/Tensorflow2/tensorflow2.h#L159) function to do GPU/CPU switching which uses a "hack" to get the raw binary internal representation of tensorflow and do a "compatible" call..!
> 
> There is no other official way to do this :(
> 
> In any case since you managed to use/run the code I am closing this issue!
> 
> Thank you again for pointing the mistaken model packaging

OK, now these saved models can be loaded successfully and predict fine.Thank you.

**Comment by Markus-x64** [comment] 2023-08-03 19:54
@AmmarkoV I think I'm seeing this same issue following the fix for cvrlcode.ics.forth.gr being down (#96 and #106). The initialize.sh script now runs 
`wget -O allInOneMNET2RedistMirrorICPR2020.zip "drive.google.com/u/3/uc?id=1GtmPWOpf3MzhqhqegaC8cS3_m3Drp6y3&export=download&confirm=yes"`

However this .zip has empty variable folders, for example `/dataset/combinedModel/mocapnet2/mode1/1.0/upperbody_all.pb/variables/` is empty and I'm getting the same issue as @polwer:
```
neuralNetworkLoad: attempting to load a TF2 style saved model (dataset/combinedModel/mocapnet2/mode1/1.0/upperbody_all.pb/saved_model.pb)..
Loading model : dataset/combinedModel/mocapnet2/mode1/1.0/upperbody_all.pb | Input : serving_default_input_all | Output : StatefulPartitionedCall
2023-08-03 19:40:50.920137: I tensorflow/cc/saved_model/reader.cc:31] Reading SavedModel from: dataset/combinedModel/mocapnet2/mode1/1.0/upperbody_all.pb
2023-08-03 19:40:51.140317: I tensorflow/cc/saved_model/reader.cc:54] Reading meta graph with tags { serve }
2023-08-03 19:40:51.140377: I tensorflow/cc/saved_model/loader.cc:250] Reading SavedModel debug info (if present) from: dataset/combinedModel/mocapnet2/mode1/1.0/upperbody_all.pb
Your MocapNET version is up to date
2023-08-03 19:40:51.830903: I tensorflow/cc/saved_model/loader.cc:215] Restoring SavedModel bundle.
2023-08-03 19:40:51.830995: I tensorflow/cc/saved_model/loader.cc:225] The specified SavedModel has no variables; no checkpoints were restored. File does not exist: dataset/combinedModel/mocapnet2/mode1/1.0/upperbody_all.pb/variables/variables.index
2023-08-03 19:40:51.831007: I tensorflow/cc/saved_model/loader.cc:199] Running initialization op on SavedModel bundle at path: dataset/combinedModel/mocapnet2/mode1/1.0/upperbody_all.pb
2023-08-03 19:40:52.511864: I tensorflow/cc/saved_model/loader.cc:319] SavedModel load for tags { serve }; Status: success: OK. Took 1591721 microseconds.
Caching networks after initialization to be ready for use..
tf2_run: Error running dataset/combinedModel/mocapnet2/mode1/1.0/upperbody_all.pb network, Error while reading resource variable head_Zrotation_15_layer_12/bias from Container: localhost. This could mean that the variable was uninitialized. Not found: Container localhost does not exist. (Could not find resource: localhost/head_Zrotation_15_layer_12/bias)
         [[{{node model/head_Zrotation/head_Zrotation_15_layer_12/BiasAdd/ReadVariableOp}}]]
dimensionsNumber=2
dataSizeBytes=1288
The given SavedModel SignatureDef contains the following input(s):
  inputs['input_all'] tensor_info:
      dtype: DT_FLOAT
      shape: (-1, 322)
      name: serving_default_input_all:0
The given SavedModel SignatureDef contains the following output(s):
  outputs['result_all'] tensor_info:
      dtype: DT_FLOAT
      shape: (-1, 42)
      name: StatefulPartitionedCall:0
Method name is: tensorflow/serving/predict
Segmentation fault (core dumped)
```

I'm trying to run MocapNET inside a docker container using the cpu version of Tensorflow. I have installed OpenCV 4.5 in the container while Tensorflow gets built by the initialize.sh script. This is the command I use to produce the above error:
`./MocapNET2LiveWebcamDemo --from shuffle.webm --openpose --frames 375 --novisualization`

Did @AmmarkoV  forget to add the variables to this new .zip file?
