### ISSUE TITLE
Why is the motion capture applied to the model not smooth?

### ISSUE THREAD

**Issue by delebash** [FORTH-ModelBasedTracker/MocapNET#18] opened 2020-05-29 23:58 UTC
In your video example of using makehuman, blender, and applying out.bvh the model motion is not very smooth.  It seems to be moving/jumping around.

I created the same animation using your example from openpose data and got the same results.

What am I doing wrong?

**Comment by AmmarkoV** [comment] 2020-06-09 08:54
Hello, please specify which tool and what commandline parameters you are using, and which dataset so I can check for any new bugs etc..

However, and as stated in the [original method video](https://www.youtube.com/watch?v=fH5e-KMBvM0#t=3m58s) keep in mind that each frame of input is treated as standalone so there is no tracking or smoothing applied in the output in the original work ( This was a choice to accurately showcase the exact output of the neural network ). This is bad when you are dealing with videos but good and important since you can actually feed MocapNET arbitrary streams of images and they don't have to be consecutive frames. 

After the BMVC 2019 publication and due to all relevant methods having some sort of smoothing function, I have added a post-processing smoothing step [Butterworth smoothing filter](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/src/MocapNET1/MocapNETLib/outputFiltering.hpp) that is switched on by default.

The jumping you are referring, if it is not some sort of bug introduced by a recent commit, can be caused by a multitude of reasons  :

- It can be caused by not providing the correct dimensions of your input.  For example giving the parameters [--size 1920 1080](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/src/MocapNET1/MocapNETFromJSON/mocapnetJSON.cpp#L194) for a 1920x1080 stream. This might seem trivial but since the neural network relies on normalized coordinates supplying a wrong frame size destroys the normalization and can lead to very weird artifacts like the jumping you describe.

- It can be caused by turning off the post-processing filtering I mentioned above ( if you give the --nofilter command line parameter ). 

- It can be caused by turning off the positional constraints (if you give the --unconstrained command line parameter ) 

- It can be caused by 2D joint estimator error ( This is applicable for the live demo where sometime the 2D joint estimator mixes up right/left knees and then this adversely affects 3D estimation ) To make this better for the MocapNETLiveWebcamDemo  you can try to run using the --openpose parameter to enforce a better and more precise 2D estimator ( albeit slower ). If you use regular OpenPose .json/.csv files this is probably not an issue however.

- It can be caused by having multiple persons visible on the screen. For example [in this video](https://www.youtube.com/watch?v=fH5e-KMBvM0#t=3m37s)  at 3:37 with the two people dancing side by side the 2D joint estimator jumps from one to the other and this leads of course to the 3D joint estimator jumping as well  The method ( for now ) is a single person pose estimator and if you have multiple persons on screen joints with the highest 2D score get picked and can create weird skeletons that result in weird jumping behavior.

- It can be caused by neural network noise/failure.  Despite the training perturbations and randomizations and elaborate setup truth be told the neural network is a black box and for specific poses sometimes responds in a noisy way. In the [new version of the method/software](http://ammar.gr/mocapnet/mnet2/newversion.webm)  these issues are much less pronounced. The new version has been submitted and is pending peer-review.. Hopefully after a positive review I will be able to commit here the new version here and it will probably solve your issues, if they are not solved by remedying the issues mentioned  above,  since it architecturally works much better than the original version.

**Comment by delebash** [comment] 2020-06-09 20:29
Thanks.  I will do some testing in reference to your comments and see what I can find out.  I really appreciate your help and you have done an excellent job with this software.  I am looking forward to the new version.

**Comment by AmmarkoV** [comment] 2020-10-12 19:38
The motion is much smoother than previous version [after transitioning to MNET2](https://github.com/FORTH-ModelBasedTracker/MocapNET/commit/5e0c8d41e7afba7266cba0e239abe40a51aad950)  so I am closing this issue, if you are still having problems feel free to open a new one..!

**Closed as completed by AmmarkoV** 2020-10-12 19:38 UTC
Labels: documentation, alreadyimplementedpendingpublication
